version: "3"
  
services:
  dockerhub-rate-limit-exporter:
    # image: tcaty/dockerhub-rate-limit-exporter
    build:
      context: ../../
      dockerfile: Dockerfile
    command: scrape
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.51.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - dockerhub-rate-limit-exporter
      
  grafana:
    image: grafana/grafana:10.4.1
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ../shared/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../shared/grafana-providers.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ../shared/grafana-dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
