version: "3"
  
services:
  # authenticated instance will have increased rate limits
  # according to dockerhub docs they are 200 pulls per 6 hour period
  dockerhub-rate-limit-exporter-authenticated:
    build:
      context: ../../
      dockerfile: Dockerfile
    command: scrape --log-level DEBUG
    environment:
      USERNAME: ${DOCKERHUB_USERNAME}
      PASSWORD: ${DOCKERHUB_PASSWORD}
    ports:
      - "8080:8080"
        
  # exporter in anonymous mode has default rate limits
  # according to dockerhub docs they equals to 100 pulls per 6 hours per IP address
  dockerhub-rate-limit-exporter-anonymous:
    build:
      context: ../../
      dockerfile: Dockerfile
    command: scrape --log-level DEBUG
    ports:
      - "8081:8080"

  prometheus:
    image: prom/prometheus:v2.51.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - dockerhub-rate-limit-exporter-authenticated
      - dockerhub-rate-limit-exporter-anonymous
      
  grafana:
    image: grafana/grafana:10.4.1
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    volumes:
      - ../shared/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ../shared/grafana-providers.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ../shared/grafana-dashboard.json:/var/lib/grafana/dashboards/dashboard.json
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
